services:
  app:
    build: .
    container_name: TechnicalTestWexApplication
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/TechnicalTestWex
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=P4s5w0rd
    networks:
      - app-network
    restart: always

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=P4s5w0rd
      - MYSQL_DATABASE=TechnicalTestWex
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
        - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: